
// Objective-C API for talking to the following Go packages
//
//	github.com/Ncog-Earth-Chain/Web-Assembly-Go/mobile_apps
//
// File is generated by gomobile bind. Do not edit.
#ifndef __MobileApps_FRAMEWORK_H__
#define __MobileApps_FRAMEWORK_H__

#include "Mobile_apps.objc.h"
#include "Universe.objc.h"

#endif
