// Objective-C API for talking to github.com/Ncog-Earth-Chain/Web-Assembly-Go/mobile_apps Go package.
//   gobind -lang=objc github.com/Ncog-Earth-Chain/Web-Assembly-Go/mobile_apps
//
// File is generated by gobind. Do not edit.

#ifndef __Mobile_apps_H__
#define __Mobile_apps_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class Mobile_appsDecodedRLP;
@class Mobile_appsEncryptedResult;
@class Mobile_appsKeyPair;
@class Mobile_appsSignedTxResult;

@interface Mobile_appsDecodedRLP : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped field DecodedRLP.Fields with unsupported type: []string

@property (nonatomic) long count;
@end

@interface Mobile_appsEncryptedResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull encrypted;
@property (nonatomic) NSString* _Nonnull version;
@end

@interface Mobile_appsKeyPair : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull pubKey;
@property (nonatomic) NSString* _Nonnull privKey;
@end

@interface Mobile_appsSignedTxResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull rawTransaction;
@property (nonatomic) NSString* _Nonnull hash;
@end

/**
 * 8. Decode RLP Transaction
 */
FOUNDATION_EXPORT Mobile_appsDecodedRLP* _Nullable Mobile_appsDecodeRLPTransactionMobile(NSString* _Nullable rlpHex, NSError* _Nullable* _Nullable error);

/**
 * 3. Asymmetric Decryption
 */
FOUNDATION_EXPORT NSString* _Nonnull Mobile_appsDecryptMobile(NSString* _Nullable privKeyHex, NSString* _Nullable encryptedData, NSString* _Nullable version, NSError* _Nullable* _Nullable error);

/**
 * 2. Asymmetric Encryption
 */
FOUNDATION_EXPORT Mobile_appsEncryptedResult* _Nullable Mobile_appsEncryptMobile(NSString* _Nullable pubKeyHex, NSString* _Nullable message, NSError* _Nullable* _Nullable error);

/**
 * 1. Key Generation
 */
FOUNDATION_EXPORT Mobile_appsKeyPair* _Nullable Mobile_appsKeyGenMobile(NSError* _Nullable* _Nullable error);

/**
 * 6. Private Key to Wallet Address
 */
FOUNDATION_EXPORT NSString* _Nonnull Mobile_appsPrivateKeyToWalletAddressMobile(NSString* _Nullable privateKeyHex, NSError* _Nullable* _Nullable error);

/**
 * 7. Sign Transaction
 */
FOUNDATION_EXPORT Mobile_appsSignedTxResult* _Nullable Mobile_appsSignTransactionMobile(NSString* _Nullable txArgsJSON, NSString* _Nullable privKeyHex, NSError* _Nullable* _Nullable error);

/**
 * 5. Symmetric Decryption
 */
FOUNDATION_EXPORT NSString* _Nonnull Mobile_appsSymDecryptMobile(NSString* _Nullable ssKeyHex, NSString* _Nullable encryptedData, NSString* _Nullable version, NSError* _Nullable* _Nullable error);

/**
 * 4. Symmetric Encryption
 */
FOUNDATION_EXPORT Mobile_appsEncryptedResult* _Nullable Mobile_appsSymEncryptMobile(NSString* _Nullable ssKeyHex, NSString* _Nullable message, NSError* _Nullable* _Nullable error);

#endif
